set belloff=all
set colorcolumn=80
set cursorline
set expandtab
set history=1000
set ignorecase
set incsearch
set mouse=a
set nobackup
set nocompatible
set number
set scrolloff=10
set shiftwidth=2
set showcmd
set showmatch
set showmode
set signcolumn=yes
set smartcase
set smartindent
set softtabstop=2
set tabstop=2
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildmenu
set wildmode=list:longest
